name: Build CV (HTML only)

on:
  push:
    branches: [ main ]
    paths:
      - "cv/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Debug - show files
        run: |
          ls -la
          ls -la cv
          quarto --version

      - name: Render CV (HTML)
        run: |
          cd cv
          quarto render cv.qmd --to html
          ls -la
